backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/pages/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'blog-post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Featured Post', name: 'featuredpost', widget: 'boolean' }
      - { label: 'Featured Image', name: 'featuredimage', widget: image }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Landing Page'
        name: 'index'
        fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'index-page' }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - {
              label: Mainpitch,
              name: mainpitch,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: 'Beskrivning',
                    name: 'beskrivning',
                    widget: list,
                    fields: [{ label: Stycke, name: stycke, widget: text }],
                  },
                ],
            }
          - {
              label: Historia,
              name: historia,
              widget: object,
              fields:
                [
                  { label: Rubrik, name: rubrik, widget: string },
                  { label: Text, name: text, widget: list, fields: [{ label: Stycke, name: stycke, widget: text }] },
                  { label: Bild, name: bild, widget: image },
                ],
            }
          - {
              label: Personser,
              name: personer,
              widget: object,
              fields:
                [
                  { label: Rubrik, name: rubrik, widget: string },
                  { label: Text, name: text, widget: list, fields: [{ label: Stycke, name: stycke, widget: text }] },
                  {
                    label: Bild,
                    name: bild,
                    widget: list,
                    fields:
                      [
                        { label: Namn, name: namn, widget: text },
                        { label: Titel, name: titel, widget: text },
                        { label: Telefon, name: telefon, widget: text },
                        { label: Fax, name: fax, widget: text },
                        { label: Mail, name: mail, widget: text },
                        { label: Bild, name: bild, widget: image },
                      ],
                  },
                ],
            }
          - {
              label: Kontakt,
              name: kontakt,
              widget: object,
              fields:
                [
                  { label: Rubrik, name: rubrik, widget: string },
                  { label: Text, name: text, widget: list, fields: [{ label: Stycke, name: stycke, widget: text }] },
                  { label: Bild, name: bild, widget: image },
                ],
            }
      - file: 'src/pages/startsida/index.md'
        label: 'Startsida'
        name: 'startsida'
        fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'startsida-page' }
          - { label: 'Rubrik', name: 'rubrik', widget: 'string' }
          - { label: 'Underrubrik', name: 'underrubrik', widget: 'string' }
          - {
              label: 'Left',
              name: 'left',
              widget: object,
              fields: [{ label: Image, name: image, widget: image }, { label: Text, name: text, widget: string }],
            }
          - {
              label: 'Center',
              name: 'center',
              widget: object,
              fields: [{ label: Image, name: image, widget: image }, { label: Text, name: text, widget: string }],
            }
          - {
              label: 'Right',
              name: 'right',
              widget: object,
              fields: [{ label: Image, name: image, widget: image }, { label: Text, name: text, widget: string }],
            }
      - file: 'src/pages/footer/index.md'
        label: 'Footer'
        name: 'footer'
        fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'footer' }
          - { label: 'Left', name: 'left', widget: list, fields: [{ label: Stycke, name: stycke, widget: text }] }
          - { label: 'Right', name: 'right', widget: list, fields: [{ label: Stycke, name: stycke, widget: text }] }
      - file: 'src/pages/about/index.md'
        label: 'About'
        name: 'about'
        fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'about-page' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
